Istio intro adoc
OpenLiberty/guides-common pull request #523
Opened 2020-10-16 21:07 UTC by tt-le

New common adoc for deployment of istio using `istioctl`

2020-10-22 18:57 UTC, gkwan-ibm requested changes

2020-10-22 18:57 UTC, gkwan-ibm commented on istio-start.adoc
> +We will use the following command to configure the {istio} profile on {kube}
@tt-le Should not use the first person words `We`, `I`. `our`, etc. Suggest "We will use..." -> "Use ..."

2020-10-22 18:59 UTC, gkwan-ibm commented
@tt-le is `deploy-istio.adoc` better than `istio-start.adoc` ?

2020-10-27 18:45 UTC, Charlotte-Holt reviewed
@tt-le I added some minor ID review comments. Let me know if you have any questions!

2020-10-27 18:45 UTC, Charlotte-Holt commented on istio-start.adoc
> +Run the following command to verify that `istioctl` path has been set successfully:
Suggested update:

>Run the following command to verify that the `istioctl` path was set successfully:

2020-10-27 18:45 UTC, Charlotte-Holt commented on istio-start.adoc
> +Install {istio} by following the instructions in the official https://istio.io/latest/docs/setup/getting-started[{istio} Getting started^] documentation.
Include "documentation" in the link text.

2020-10-27 18:45 UTC, Charlotte-Holt commented on istio-start.adoc
> +The output will be similar to the following example.
Add a colon after "The output will be similar to the following example"

2020-10-27 18:45 UTC, Charlotte-Holt commented on istio-start.adoc
> +Use the following command to configure the {istio} profile on {kube}
Suggested update

>Run the following command to configure the {istio} profile on {kube}:

2020-10-27 18:45 UTC, Charlotte-Holt commented on istio-start.adoc
> +The following output should appear when the installation is complete:
Suggested update

>The following output appears when the installation is complete:

2020-10-27 18:45 UTC, Charlotte-Holt commented on istio-start.adoc
> +Ensure that the {istio} deployments are all available before you continue. The deployments might take a few minutes to become available. If the deployments aren't available after a few minutes, then
Suggested update

>On {minikube}, you can increase the memory using the `--memory` flag.

To

>On {minikube}, you can increase the memory by using the `--memory` flag.

2020-10-27 18:45 UTC, Charlotte-Holt commented on istio-start.adoc
> +Finally, create the `istio-injection` label and set its value to `enabled`.
Add a colon after "Finally, create the `istio-injection` label and set its value to `enabled`"

2020-10-27 18:45 UTC, Charlotte-Holt commented on istio-start.adoc
> +automatically be injected into your pods when you deploy your application.
Suggested update

>Automatic injection means that sidecars will automatically be injected into your pods when you deploy your application.

To

>Automatic injection means that sidecars are automatically injected into your pods when you deploy your application.

2020-10-28 01:16 UTC, tt-le commented
@Charlotte-Holt Thank you for your feedback, I just addressed it. What do you think now?

2020-10-28 13:32 UTC, Charlotte-Holt approved these changes
@tt-le LGTM, thx!

2020-10-28 23:06 UTC, gkwan-ibm approved these changes

2020-10-28 23:06 UTC, merged