Fixes #668
OpenLiberty/guides-common pull request #687
Opened 2021-06-28 21:38 UTC by priyyanshi

2021-06-29 14:10 UTC, tt-le approved these changes
LGTM

2021-07-05 16:45 UTC, gkwan-ibm requested changes

2021-07-05 16:45 UTC, gkwan-ibm commented on pr-checker/checker.py
> +    file_tags_re = re.compile("^.*(hide_tags=).*(tags=).*$")
@priyyanshi @tt-le 
should it be `file_tags_re = re.compile("^.*(tags=).*(hide_tags=).*$")`?

2021-07-05 16:47 UTC, gkwan-ibm approved these changes

2021-07-05 16:47 UTC, merged